# Generated by Django 6.0.6 on 2026-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customvideomodel_height_customvideomodel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvideomodel',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
