# Generated by Django 6.0.6 on 2026-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
